'use strict';
// References stay hidden until a trained model and a finished arena trial exist.
async function showReferences(){
 references=await api('references');tab='references';head();
 if(!references.unlocked){
  $('stage').innerHTML=`<section class="panel"><span class="eyebrow">FINAL COMPARISON</span><h2>Your experiments first. The references come last.</h2><p>Finish training and an arena trial, then reveal two different paths.</p><div class="reference-checks"><p>${references.requirements.trained?'✓':'○'} A saved neural model</p><p>${references.requirements.arena_completed?'✓':'○'} A finished arena trial (capped games remain unfinished results)</p></div><button id="reveal-references" class="primary" ${references.eligible?'':'disabled'}>Reveal the final references</button><p class="muted">References appear in opponent choices after you reveal them. Restarting the server resets the reveal.</p></section>`;
  $('reveal-references').onclick=()=>act(async()=>{references=await api('references/reveal',{});await showReferences();});
  await appendRoadmap();
  return;
 }
 const p=references.prepared;
 $('stage').innerHTML=`<div class="layout"><section class="panel"><span class="eyebrow">PATH A · SAME NETWORK</span><h2>Prepared Neural Panda 🐼</h2>${p?metrics([['Validation MSE',errorValue(p.validation.mse)],['Test MSE',errorValue(p.test.mse)],['Practice positions',p.count]])+'<p>Same 782 → 32 → 1 architecture. More practice boards, Adam updates, and a checkpoint selected by validation error.</p>'+metrics([['Selected epoch',p.epoch],['Updates attempted',p.epochs_run],['Preparation seconds',p.seconds]])+`<p class="muted">Seed ${p.seed} · step size ${p.rate}. Test uses ${p.test.n} boards, measured after checkpoint selection. These errors are not percentages or chess ratings.</p><button id="play-prepared" class="primary">Play prepared Panda</button><details class="advanced"><summary>See training and overfitting</summary>${plot(p.history)}<p>Training error can keep falling while validation error rises. We retained epoch ${p.epoch}, rather than the final update. No test board selected the checkpoint.</p></details>`:'<p>Not prepared on this computer. Run <code>python -m training.prepare_reference</code> before starting the app.</p>'}</section><section class="panel"><span class="eyebrow">PATH B · DIFFERENT ENGINE</span><h2>Stockfish · external reference 🐟</h2><p>Pretrained NNUE evaluation plus a mature search engine. It was developed by the Stockfish community; our demo did not train it.</p>${references.stockfish_ready?'<span class="badge">Local engine ready</span><p>Uses 1 CPU thread, 32 MiB hash, and a 0.3-second analysis limit. Process startup adds time.</p><button id="play-stockfish" class="primary">Play Stockfish</button>':'<p class="warning">Not installed here. Download the official build for your OS; place its executable in <code>external/stockfish</code> (or <code>external/stockfish.exe</code>), then restart.</p>'}<p class="muted">No comparable teacher-prediction error is claimed for Stockfish. Evaluate its decisions and games separately.</p><a href="https://stockfishchess.org/download/" target="_blank" rel="noopener">Official downloads ↗</a></section><section class="panel wide"><h2>Same board. Different decisions.</h2><div class="controls"><label>Position<select id="reference-position"><option value="current">Current playable board</option><option value="start">Starting position</option><option value="queen">Can you take the free queen?</option><option value="trap">A tempting rook capture</option></select></label><button id="compare-references" class="primary">Compare moves & error</button><button id="reference-arena">Test in Arena →</button></div><p class="muted">Panda models: depth 2, 3,000 nodes each. Stockfish: its own search, 0.3 seconds. This illustrates two systems; it is not an equal-compute strength test. Prediction errors use the same 400 validation boards.</p><div id="reference-comparison"></div></section></div>`;
 await appendRoadmap();
 if(p)$('play-prepared').onclick=()=>act(async()=>{bot='reference-neural';hintEngine='reference-neural';ownHint=null;await show('play');});
 if(references.stockfish_ready)$('play-stockfish').onclick=()=>act(async()=>{bot='reference-stockfish';hintEngine='reference-stockfish';ownHint=null;await show('play');});
 $('reference-arena').onclick=()=>act(()=>show('arena'));
 $('compare-references').onclick=()=>act(async()=>{
  const r=await api('references/compare',{example:$('reference-position').value,moves});
  const improvement=r.reference?100*(r.student.mse-r.reference.mse)/r.student.mse:null;
  $('reference-comparison').innerHTML=`<h3>Validation prediction error</h3>${metrics([['Your loaded model · '+r.student_id,errorValue(r.student.mse)],['Prepared Panda',r.reference?errorValue(r.reference.mse):'Unavailable'],['Reference error reduction',improvement===null?'—':improvement.toFixed(1)+'%']])}<p class="muted">A negative reduction means your model has lower error. This is a reduction in MSE, not an accuracy percentage. Neither model is guaranteed to win.</p><div class="reference-layout"><div><h3>Comparison position · view only</h3><div id="reference-board" class="board"></div></div><div><h3>Moves chosen</h3><table><tr><th>Engine</th><th>Move</th><th>White score</th><th>Look ahead</th></tr>${r.choices.map((c,i)=>`<tr><td>${name(c.engine)}</td><td>${c.san||'Game over'}</td><td>${candidateScore(c.score)}</td><td><button data-reference-leaf="${i}">Inspect line</button></td></tr>`).join('')}</table><p class="muted">Scores come from different evaluators and are not interchangeable. + favors White; − favors Black.</p><div id="reference-line"></div></div></div>`;
  board('reference-board',r.board);
  stopContinuation();
  document.querySelectorAll('[data-reference-leaf]').forEach(b=>b.onclick=()=>act(async()=>{const c=r.choices[Number(b.dataset.referenceLeaf)];await previewContinuation('reference-line',{fen:r.board.fen},c.pv,`${name(c.engine)} · searched continuation`,null,false,true);}));
 });
}

async function appendRoadmap(){
 const games=await api('games');
 const section=document.createElement('section');section.className='panel roadmap';
 section.innerHTML=`<span class="eyebrow">KEEP BUILDING</span><h2>Roadmap &amp; future possibilities</h2><p>Make the take-home project your own. Choose one improvement, keep a baseline, then test what changed in the Arena.</p><table><thead><tr><th>Try next</th><th>What you could build</th><th>How to check it</th></tr></thead><tbody><tr><td>Give Panda a personality</td><td>Adjust material, mobility or king-safety evaluation.</td><td>Compare moves on the same positions and play paired matches.</td></tr><tr><td>Search more efficiently</td><td>Add a transposition table or quiescence search.</td><td>Compare tactics solved, nodes and time with the original engine.</td></tr><tr><td>Learn from your games</td><td>Label saved PGN positions with Stockfish, then train a new version.</td><td>Keep whole games separate across training and validation; test against the previous model.</td></tr><tr><td>Improve the neural evaluator</td><td>Try more diverse data, a different network or training settings.</td><td>Compare validation error and Arena results; lower error alone does not prove stronger chess.</td></tr><tr><td>Explore self-play</td><td>Build a pipeline that learns from completed game outcomes.</td><td>Test each challenger against fixed opponents before replacing the champion.</td></tr><tr><td>Take an advanced path</td><td>Explore policy/value networks with Monte Carlo Tree Search.</td><td>Start small and compare performance under a fixed time budget.</td></tr></tbody></table><p class="muted">These are extension ideas, not features already running. Playing or saving a game does not automatically train a model.</p><details class="advanced"><summary>Saved games — starting material for your own experiments</summary><p>Completed and unfinished PGNs keep their actual result. These files have not been labeled or added to training.</p><div id="roadmap-games"></div></details>`;
 const list=section.querySelector('#roadmap-games');
 if(!games.length)list.textContent='No saved games yet. Play a game and choose Save game (PGN).';
 for(const game of games){const row=document.createElement('p'),link=document.createElement('a');link.href='/pgn/'+encodeURIComponent(game);link.target='_blank';link.rel='noopener';link.textContent=game+' ↗';row.append(link);list.append(row);}
 $('stage').append(section);
}
