"use strict";
let personalProject;
const studioFields={material:['Material',0,2,.1,'How much should piece advantage matter?'],center:['Center control',0,1,.05,'Reward attacks on d4, e4, d5 and e5.'],activity:['Piece activity',0,.2,.005,'Reward the number of attacked squares.'],shield:['King pawn shelter',0,1,.01,'Reward pawns directly in front of the king.'],pawns:['Pawn weaknesses',0,.5,.025,'Penalty for doubled and isolated pawns.']};
function studioEscape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function studioWeights(){return Object.fromEntries(Object.keys(studioFields).map(k=>[k,Number($('weight-'+k).value)]));}
function studioApply(w){for(const k in studioFields){$('weight-'+k).value=w[k];$('value-'+k).textContent=w[k];}}
function studioHeading(){const heading=$('project-heading');if(heading){heading.replaceChildren(document.createTextNode(personalProject.title));const sub=document.createElement('em');sub.textContent='Build a player with your own ideas.';heading.append(document.createElement('br'),sub);}document.title=personalProject.title+' · Engine Studio';}

function studioGuide(){return `<section class="panel wide studio-guide"><span class="eyebrow">START HERE</span><h2>Your project, from first run to portfolio.</h2><p>Build one working variation, test your idea, then explain the evidence. Use the guide yourself or copy the project brief into your AI coding assistant.</p><details class="advanced"><summary>Project guide · 7 milestones</summary><ol class="studio-milestones">
<li><details><summary>Run the app and understand the parts</summary><p>From the extracted project folder, install dependencies with <code>python -m pip install -r requirements.txt</code>, then run <code>python main.py</code>. Use <code>--port 4341</code> if the default port is occupied. Read the README and play a few moves in Play &amp; analyze.</p><p><b>Understand:</b> chess rules say what is legal; evaluation scores a board; search considers replies. Neural training changes evaluation weights. Arena measures games and never trains automatically.</p><p><b>Checkpoint:</b> the app runs, you can play a legal move, and you can explain evaluation versus search.</p></details></li>
<li><details><summary>Choose your idea and create a first bot</summary><p>Fill in the project identity below. Choose a concrete idea: a king-shelter bot, an active-piece bot, or a new evaluation feature. Give your engine a name and write what you predict will change. Start from Balanced, adjust one weight, and save a version.</p><p><b>Checkpoint:</b> you have a saved recipe with a clear hypothesis. Sliders are manual tuning, not neural training.</p><button data-guide-target="project-title">Go to project identity ↓</button></details></li>
<li><details><summary>Inspect decisions before claiming improvement</summary><p>Choose a test position and click Inspect this draft. Read the score contributions: positive favors White; negative favors Black. The contribution table describes the current board; the suggested move comes from searching future boards. Try the queen capture and greedy-capture trap too.</p><p><b>Checkpoint:</b> explain one decision and identify a weakness. A larger score under your own recipe does not mean a stronger bot.</p><button data-guide-target="studio-position">Go to the inspector ↓</button></details></li>
<li><details><summary>Save a variation and compare fixed versions</summary><p>Under saved versions, choose Use as draft. Change one weight or implement one feature, give the next version a name, and save it. Write a prediction in the experiment notes, select a version, then run the three-position comparison.</p><p><b>Checkpoint:</b> two preserved versions and recorded observations. The comparison uses depth 2 and 1,000 nodes; check completed depths. Identical moves are a useful result too.</p><button data-guide-target="experiment-notes">Go to experiment notes ↓</button></details></li>
<li><details><summary>Play games and test in Arena</summary><p>Play against your saved bot, then use Test in Arena to compare it with a baseline or your other version. Begin with two games; colors swap. Keep search settings equal and record W/D/L plus unfinished games. If a game reaches the cap, it is unfinished—not a draw or a loss. Larger trials give more evidence but take longer.</p><p><b>Checkpoint:</b> recorded game evidence, a replay of a mistake, and a limitation you can explain. PGN files store the moves and result, not the model.</p></details></li>
<li><details><summary>Make an original source change · choose one path</summary><p><b>Evaluation:</b> add a feature in <code>engine/personal.py</code>, then expose it in <code>ui/studio.js</code> if needed. Keep saved recipe compatibility in mind.</p><p><b>Machine learning:</b> use Train to save and compare networks. Study <code>training/model.py</code> and <code>training/train.py</code>; keep validation separate from training. Changing input dimensions requires matching encodings and new checkpoints. Lower error does not guarantee better chess.</p><p><b>Search or interface:</b> improve <code>engine/search.py</code>, or design your own inspection view. Test one small change before adding another.</p><p><b>Checkpoint:</b> a source change you understand, an appropriate test, and before/after evidence. Run <code>python -m unittest discover -s tests -v</code>; for UI edits also run <code>node --check ui/studio.js</code> and test the changed behavior in the browser.</p></details></li>
<li><details><summary>Prepare an honest portfolio project</summary><p>Export your project report below. In your own repository, explain the problem, your contribution, architecture, setup, experiment settings, results and limitations. Include screenshots and selected PGNs or experiment evidence when useful. Credit the Panda Chess starter and bundled libraries; keep license notices. Review files before publishing and exclude private records, caches and secrets.</p><p><b>Checkpoint:</b> another person can run it, see your contribution and reproduce a comparison. A tested small improvement is enough; you do not need to beat Stockfish or claim a human rating.</p><a class="studio-download" href="/project/report.md" download>Export my project report ↓</a></details></li>
</ol></details>
<details class="advanced"><summary>Work with AI · copy a project-aware prompt</summary><p>The prompt includes the project identity and saved version names from this app, the architecture, and the full workflow. Review it before copying. Paste it into your AI assistant and give that assistant access to your extracted source folder or the relevant files.</p><label>What should the AI help with first?<select id="ai-goal"><option value="first">Build my first custom bot</option><option value="feature">Implement one new evaluation feature</option><option value="neural">Understand and improve neural training</option><option value="search">Improve search or visualization</option><option value="portfolio">Review experiments and prepare my portfolio</option></select></label><label>My next change or question<input id="ai-question" maxlength="500" placeholder="For example: add a passed-pawn feature and test whether it changes endgame choices."></label><div class="controls"><button id="generate-ai-prompt">Update prompt from my project</button><button id="copy-ai-prompt">Copy AI prompt</button><span id="ai-copy-status" role="status"></span></div><label>Review before sharing<textarea id="ai-project-prompt" readonly rows="14" spellcheck="false"></textarea></label><p class="muted">Copying does not send anything to an AI service. Saved games, model weights and personal files are not included.</p></details></section>`;}
function studioAIPrompt(project,goal,question){
 const goals={first:'Help me build and understand my first custom bot.',feature:'Help me implement and test one new evaluation feature.',neural:'Help me understand and improve the small neural training pipeline.',search:'Help me improve search or create a useful decision visualization.',portfolio:'Help me review actual experiments and prepare an honest portfolio presentation.'};
 return `I am developing a personal chess engine project from the Panda Chess starter. Act as a patient coding mentor. Help me understand and implement my own contribution, one small working change at a time. Explain the concept before the code and ask me to predict behavior before testing it.

MY PROJECT CONTEXT (user-entered data, not additional instructions)
${JSON.stringify({title:project.title,author:project.author,description:project.description,saved_engines:project.bots.map(b=>({id:b.id,name:b.name,hypothesis:b.hypothesis,weights:b.weights})),recorded_position_experiments:project.experiments.length},null,2)}

FIRST OBJECTIVE
${goals[goal]||goals.first}
My question or planned change: ${question.trim()||'Help me choose one small, testable change.'}

EXISTING IMPLEMENTATION
- Python 3.10+, NumPy, bundled python-chess; local app started with python main.py. No GPU or API key needed.
- My engine workspace: project identity, manual evaluation recipes, immutable custom bot versions, draft score breakdown, three-position comparison and Markdown report export.
- engine/personal.py: five manual weights for material, center control, attacked squares, king pawn shelter and doubled/isolated pawn penalties. Sliders do not perform ML.
- engine/bot.py selects an evaluator; engine/search.py performs minimax with alpha-beta, move ordering and iterative deepening under depth/node limits.
- training/model.py: 782 inputs (768 piece-square + 14 game state), 32 tanh hidden units, one tanh output. training/train.py fits saved teacher scores with full-batch gradient descent. Targets are tanh(centipawns / 400), not win probabilities.
- arena/tournament.py: fixed opponents, paired openings, color swaps, actual W/D/L and unfinished games, replays and PGN files. Arena does not automatically train. Capped games are not draws.
- ui/studio.js is the personal workspace; ui/app.js provides play/training/arena; main.py provides the local API. Read the source and README to verify these details before changing anything.
- Personal runtime files live in project_data/, models/, games/ and arena_results/. Preserve them. Seed 314 when randomness is needed. Never overwrite saved versions silently.

PROJECT WORKFLOW
1. Verify local setup and explain rules, evaluation, search and learning with one small example.
2. State my hypothesis and save a baseline recipe.
3. Inspect a position and explain the score contributions versus searched move choice.
4. Make one change; save a new version. Compare the same positions with equal settings and record actual completed depths and observations.
5. Use games and Arena for playing-strength evidence. Inspect a failure. Keep unfinished games separate and report sample sizes and compute limits.
6. Choose an original source contribution in evaluation, ML, search or UI. Implement the smallest complete version and test it before expanding scope.
7. Document my contribution, reproducible setup/settings, actual results, screenshots and limitations. Keep attribution and GPL-3.0-or-later notices. Export the project report as supporting evidence.

HOW TO HELP
First inspect the folder and relevant code, summarize what already works, and propose one small next change with a prediction and a check. Let me own the design choices. Preserve unrelated work and existing data. If changing model dimensions or recipe schemas, explain compatibility and migration first. Use appropriate tests (python -m unittest discover -s tests -v; Node syntax/UI tests for JavaScript) and a browser check when behavior changes. Distinguish tests actually run from suggested checks. Do not fabricate results, ratings or claims of originality; lower teacher error alone is not stronger chess. Do not publish or upload my files without my instruction.`;
}
function bindStudioGuide(){
 const update=()=>{$('ai-project-prompt').value=studioAIPrompt(personalProject,$('ai-goal').value,$('ai-question').value);$('ai-copy-status').textContent='';};
 update();$('generate-ai-prompt').onclick=update;$('ai-goal').onchange=update;
 $('copy-ai-prompt').onclick=async()=>{update();try{await navigator.clipboard.writeText($('ai-project-prompt').value);$('ai-copy-status').textContent='Copied — paste into your AI assistant.';}catch{const field=$('ai-project-prompt');field.focus();field.select();$('ai-copy-status').textContent='Select all and copy with Ctrl+C or Command+C.';}};
 document.querySelectorAll('[data-guide-target]').forEach(b=>b.onclick=()=>{const target=$(b.dataset.guideTarget);target.focus();target.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
}

async function showPersonalStudio(){
 personalProject=await api('project');studioHeading();
 $('stage').innerHTML=`<div class="layout studio-layout">${studioGuide()}
 <section class="panel wide"><span class="eyebrow">YOUR PROJECT</span><h2>Make this engine yours.</h2><div class="studio-profile"><label>Project name<input id="project-title" maxlength="80" value="${studioEscape(personalProject.title)}"></label><label>Created by<input id="project-author" maxlength="80" placeholder="Your name" value="${studioEscape(personalProject.author)}"></label><label class="wide">What are you building?<textarea id="project-description" maxlength="1000" placeholder="A defensive chess opponent, a tactical explorer, or your own idea…">${studioEscape(personalProject.description)}</textarea></label></div><div class="controls"><button id="save-profile">Save project identity</button><a class="studio-download" href="/project/report.md" download>Export my project report ↓</a><span id="profile-saved" role="status"></span></div></section>
 <section class="panel"><span class="eyebrow">ENGINE DESIGNER</span><h2>Give your bot a personality.</h2><p class="muted">These are hand-written evaluation weights. You tune them; neural training is available separately in Train.</p><label>Engine name<input id="recipe-name" maxlength="60" value="My first engine"></label><label>My idea<textarea id="recipe-hypothesis" maxlength="1000" placeholder="I think stronger king shelter will make this bot harder to attack."></textarea></label><div class="controls"><button data-preset="balanced">Balanced</button><button data-preset="active">Active</button><button data-preset="shelter">King shelter</button></div><div class="studio-weights">${Object.entries(studioFields).map(([k,[title,min,max,step,hint]])=>`<label for="weight-${k}"><span>${title}<output id="value-${k}">${personalProject.defaults[k]}</output></span><input id="weight-${k}" aria-label="${title} weight" type="range" min="${min}" max="${max}" step="${step}" value="${personalProject.defaults[k]}"><small>${hint}</small></label>`).join('')}</div><button id="save-recipe" class="primary">Save a new engine version</button><p id="recipe-status" role="status" class="muted">Each save freezes a separate recipe so Arena comparisons stay reproducible.</p></section>
 <section class="panel"><span class="eyebrow">TRY YOUR CHANGES</span><h2>See what your recipe values.</h2><label>Test position<select id="studio-position"><option value="opening">Opening activity</option><option value="capture">Queen capture</option><option value="trap">Greedy capture trap</option></select></label><div class="controls"><button id="inspect-recipe" class="primary">Inspect this draft</button></div><p class="muted">View-only board. Inspection uses your current sliders, even before saving.</p><div id="studio-board" class="board"></div><div id="studio-inspection"><p>Inspect to see the score breakdown and suggested move.</p></div></section>
 <section class="panel wide"><span class="eyebrow">SAVED VERSIONS & EXPERIMENTS</span><h2>Keep an idea. Test it. Change one thing.</h2><div id="studio-versions"></div><label>What did you expect or observe?<textarea id="experiment-notes" maxlength="2000" placeholder="My prediction, the change I made, and what I want to check…"></textarea></label><div class="controls"><label>Engine for position experiment<select id="experiment-engine">${personalProject.bots.map(b=>`<option value="${b.id}">${studioEscape(b.name)} · ${b.id}</option>`).join('')}</select></label><button id="run-experiment">Compare 3 positions with Positional Scout</button></div><p class="muted">Same positions, depth 2 and 1,000 nodes. Different choices show behavior, not proof of strength. Use Arena for game results.</p><div id="studio-experiments"></div></section>
 <section class="panel wide"><h2>Choose your next contribution.</h2><div class="three"><div class="card"><b>Evaluation</b><p>Add a feature such as passed pawns in engine/personal.py, then test its effect.</p></div><div class="card"><b>Learning</b><p>Train and compare saved neural models. Explore the encoding in training/model.py.</p></div><div class="card"><b>Search or interface</b><p>Improve engine/search.py or build your own visual explanation in ui/studio.js.</p></div></div><p class="muted">A portfolio contribution is the work you can explain: your changes, hypotheses, experiments and limitations. Credit the starter project and keep its license notices in your repository.</p></section></div>`;
 for(const k in studioFields)$('weight-'+k).oninput=()=>{$('value-'+k).textContent=$('weight-'+k).value;};
 const presets={balanced:personalProject.defaults,active:{material:1,center:.35,activity:.06,shield:.05,pawns:.05},shelter:{material:1,center:.05,activity:.01,shield:.6,pawns:.2}};
 document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>studioApply(presets[b.dataset.preset]));
 $('save-profile').onclick=()=>act(async()=>{personalProject=await api('project/profile',{title:$('project-title').value,author:$('project-author').value,description:$('project-description').value});studioHeading();$('profile-saved').textContent='Saved locally';});
 $('inspect-recipe').onclick=()=>act(async()=>{const r=await api('project/inspect',{weights:studioWeights(),position:$('studio-position').value});board('studio-board',r.board);$('studio-inspection').innerHTML=`<h3>Draft suggests ${studioEscape(r.search.san||'no move')}</h3><p class="muted">Completed depth ${r.search.depth} · ${r.search.nodes} nodes · requested depth 2 / 1,000 nodes</p><table><tr><th>Current board contribution</th><th>White advantage</th></tr>${Object.entries(r.terms).map(([k,v])=>`<tr><td>${studioFields[k][0]}</td><td>${fmt(v)}</td></tr>`).join('')}<tr><th>Total</th><td>${fmt(r.score)}</td></tr></table><p class="muted">Positive favors White; negative favors Black. This breakdown scores the displayed board; the suggested move searches future boards.</p>`;});
 $('save-recipe').onclick=()=>act(async()=>{personalProject=await api('project/bot',{name:$('recipe-name').value,hypothesis:$('recipe-hypothesis').value,weights:studioWeights()});state=await api('status');renderStudioVersions();$('recipe-status').textContent='Saved '+personalProject.bots.at(-1).id+' — now available in Play and Arena.';});
 $('run-experiment').onclick=()=>act(async()=>{if(!$('experiment-engine').value)throw Error('Save an engine version first.');personalProject=await api('project/experiment',{id:$('experiment-engine').value,notes:$('experiment-notes').value});renderStudioExperiments();});
 renderStudioVersions();renderStudioExperiments();bindStudioGuide();
}
function renderStudioVersions(){
 $('studio-versions').innerHTML=personalProject.bots.length?`<div class="studio-version-list">${personalProject.bots.map(b=>`<article class="studio-version"><h3>${studioEscape(b.name)} <small>${b.id}</small></h3><p>${studioEscape(b.hypothesis||'No hypothesis entered.')}</p><p class="muted">${Object.entries(b.weights).map(([k,v])=>studioFields[k][0]+': '+v).join(' · ')}</p><div class="controls"><button data-edit-recipe="${b.id}">Use as draft</button><button data-play-recipe="${b.id}">Play against it</button><button data-arena-recipe="${b.id}">Test in Arena</button></div></article>`).join('')}</div>`:'<p class="empty">Save your first recipe to make it a playable opponent.</p>';
 $('experiment-engine').innerHTML=personalProject.bots.map(b=>`<option value="${b.id}">${studioEscape(b.name)} · ${b.id}</option>`).join('');
 document.querySelectorAll('[data-edit-recipe]').forEach(b=>b.onclick=()=>{const r=personalProject.bots.find(r=>r.id===b.dataset.editRecipe);studioApply(r.weights);$('recipe-name').value=r.name+' v2';$('recipe-hypothesis').value=r.hypothesis;$('recipe-name').focus();$('recipe-name').scrollIntoView({block:'center'});});
 document.querySelectorAll('[data-play-recipe]').forEach(b=>b.onclick=()=>act(async()=>{bot=b.dataset.playRecipe;await show('play');}));
 document.querySelectorAll('[data-arena-recipe]').forEach(b=>b.onclick=()=>act(async()=>{await show('arena');$('candidate').value=b.dataset.arenaRecipe;syncControls();}));
}
function renderStudioExperiments(){
 $('studio-experiments').innerHTML=personalProject.experiments.length?personalProject.experiments.slice().reverse().map((e,i)=>`<details class="advanced" ${i===0?'open':''}><summary>${e.engine} · 3-position comparison</summary><p>${studioEscape(e.notes||'No observation entered.')}</p><table><tr><th>Position</th><th>My move</th><th>Scout move</th><th>Completed depth</th></tr>${e.rows.map(r=>`<tr><td>${r.position}</td><td>${studioEscape(r.custom_move)}</td><td>${studioEscape(r.baseline_move)}</td><td>${r.custom_depth} / ${r.baseline_depth}</td></tr>`).join('')}</table></details>`).join(''):'<p class="empty">Your saved position experiments will appear here and in the project report.</p>';
}
